services:
  wiki:
    build: .
    ports:
      - "5050:5050"
    volumes:
      - ./wiki:/quartz/content
      - ./quartz.config.ts:/quartz/quartz.config.ts
      - ./quartz.layout.ts:/quartz/quartz.layout.ts
    environment:
      - NODE_ENV=development
